import Image from "next/image";
import Link from "next/link";
import type { EditorialProfile } from "@/lib/trainer-editorial-view";
import { safeExternalUrl } from "@/lib/trainer-editorial-view";

const Arrow = () => <span aria-hidden="true">↗</span>;
export function EditorialProfilePage({ profile }: { profile: EditorialProfile }) {
  const linkedin = safeExternalUrl(profile.linkedinUrl), website = safeExternalUrl(profile.websiteUrl);
  return <main className="min-h-screen bg-[#f6f2eb] text-[#17202b]">
    <section className="relative overflow-hidden border-b border-white/10 bg-[#111a24] text-white">
      <div className="absolute inset-0 opacity-[.07] [background-image:linear-gradient(#fff_1px,transparent_1px),linear-gradient(90deg,#fff_1px,transparent_1px)] [background-size:52px_52px]" />
      <div className="relative mx-auto max-w-[1220px] px-5 pb-20 pt-32 sm:px-8 lg:pb-24 lg:pt-36">
        <nav aria-label="Breadcrumb" className="flex items-center gap-2 overflow-hidden text-xs font-semibold text-slate-400"><Link href="/" className="focus-ring hover:text-white">Skillary</Link><span>/</span><Link href="/trainers" className="focus-ring hover:text-white">Faculty</Link><span>/</span><span className="truncate text-slate-200">{profile.name}</span></nav>
        <div className="mt-10 grid gap-10 lg:grid-cols-[260px_minmax(0,1fr)_260px] lg:gap-14">
          <aside><div className="relative aspect-[4/5] overflow-hidden rounded-2xl border border-white/10 bg-slate-800 shadow-2xl"><Image src={profile.portraitSrc} alt={`Potret profesional ${profile.name}`} fill priority sizes="260px" className="object-cover" /></div><p className="mt-5 text-xs font-bold uppercase tracking-[.18em] text-[#e4ad51]">Skillary Faculty</p><Link href="/trainers" className="focus-ring mt-4 inline-flex text-sm font-semibold text-slate-300 hover:text-white">← Semua faculty</Link></aside>
          <div className="self-center"><span className="inline-flex items-center gap-2 rounded-full border border-[#e4ad51]/40 bg-[#e4ad51]/10 px-3 py-1.5 text-xs font-bold text-[#f2c879]"><span aria-hidden="true">✦</span>{profile.designationLabel}</span><h1 className="mt-6 max-w-3xl text-4xl font-extrabold tracking-[-.04em] sm:text-5xl lg:text-[58px] lg:leading-[1.03]">{profile.name}</h1><p className="mt-5 max-w-2xl text-xl font-medium leading-8 text-slate-200">{profile.headline}</p><p className="mt-5 max-w-2xl text-base leading-7 text-slate-400">{profile.shortBio}</p>
            <ul aria-label="Keahlian utama" className="mt-7 flex flex-wrap gap-x-5 gap-y-2 text-sm font-semibold text-slate-200">{profile.expertise.slice(0,5).map(x=><li key={x} className="before:mr-2 before:text-[#e4ad51] before:content-['·']">{x}</li>)}</ul>
            <div className="mt-9 flex flex-wrap gap-3"><a href="#programs" className="focus-ring inline-flex min-h-12 items-center rounded-lg bg-[#e4ad51] px-6 text-sm font-extrabold text-[#111a24] hover:bg-[#f1c46f]">Lihat program</a><Link href="/contact" className="focus-ring inline-flex min-h-12 items-center rounded-lg border border-white/20 px-6 text-sm font-bold hover:bg-white/10">Diskusikan pelatihan</Link></div>
            {(linkedin||website)&&<div className="mt-7 flex gap-5 text-sm font-semibold text-slate-300">{linkedin&&<a className="focus-ring hover:text-white" href={linkedin} target="_blank" rel="noopener noreferrer" aria-label={`Buka LinkedIn ${profile.name}`}>LinkedIn <Arrow/></a>}{website&&<a className="focus-ring hover:text-white" href={website} target="_blank" rel="noopener noreferrer" aria-label={`Buka website ${profile.name}`}>Website <Arrow/></a>}</div>}
          </div>
          <aside className="self-center border-l border-white/10 pl-6"><p className="text-xs font-bold uppercase tracking-[.16em] text-slate-500">Tentang profil ini</p><dl className="mt-6 space-y-5 text-sm"><Info term="Designation" value={profile.designationLabel}/><Info term="Lokasi" value={profile.location}/><Info term="Bahasa" value={profile.languages.join(" · ")}/><Info term="Format" value={profile.deliveryModes.join(" · ")}/>{profile.verifiedAt&&<Info term="Terakhir ditinjau" value={formatDate(profile.verifiedAt)}/>}</dl><p className="mt-7 border-t border-white/10 pt-6 text-xs leading-5 text-slate-400">{profile.designationNote}</p><Link href="/trainer-verification" className="focus-ring mt-4 inline-flex text-xs font-bold text-[#f2c879] hover:text-white">Standar verifikasi →</Link></aside>
        </div>
      </div>
    </section>
    <section className="mx-auto grid max-w-[1220px] gap-14 px-5 py-20 sm:px-8 lg:grid-cols-[minmax(0,1fr)_300px] lg:py-28">
      <div className="max-w-3xl"><Eyebrow>Profil profesional</Eyebrow><h2 className="section-title">Tentang dan praktik profesional</h2><div className="mt-6 whitespace-pre-line text-[17px] leading-8 text-slate-600">{profile.fullBio}</div>
        {profile.outcomes.length>0&&<section className="section-block"><Eyebrow>Learning focus</Eyebrow><h2 className="section-title">Yang akan dipraktikkan peserta</h2><ol className="mt-7 divide-y divide-[#dcd3c7] border-y border-[#dcd3c7]">{profile.outcomes.map((x,i)=><li key={x} className="grid gap-3 py-5 sm:grid-cols-[42px_1fr]"><span className="text-sm font-extrabold text-[#b36b2c]">0{i+1}</span><p className="font-semibold leading-7 text-slate-700">{x}</p></li>)}</ol></section>}
        {profile.programs.length>0&&<section id="programs" className="section-block scroll-mt-24"><Eyebrow>Program</Eyebrow><h2 className="section-title">Program yang dapat dibawakan</h2><div className="mt-7 grid gap-4">{profile.programs.map(p=><article key={p.title} className="group rounded-2xl border border-[#dcd3c7] bg-[#fffaf3] p-6 transition hover:-translate-y-0.5 hover:border-[#c98a43]"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#b36b2c]">Untuk {p.audience}</p><h3 className="mt-3 text-xl font-extrabold">{p.title}</h3><p className="mt-3 leading-7 text-slate-600">{p.outcome}</p>{p.href&&<Link href={p.href} className="focus-ring mt-5 inline-flex text-sm font-bold text-[#9a5421]">Pelajari program →</Link>}</article>)}</div></section>}
        {profile.teachingApproach.length>0&&<section className="section-block"><Eyebrow>Teaching approach</Eyebrow><h2 className="section-title">Cara sesi dirancang</h2><div className="mt-7 grid gap-5 sm:grid-cols-2">{profile.teachingApproach.map((x,i)=><article key={x.title} className="border-l-2 border-[#d6a253] pl-5"><span className="text-xs font-extrabold text-slate-400">0{i+1}</span><h3 className="mt-2 font-extrabold">{x.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{x.description}</p></article>)}</div></section>}
        {profile.evidence.length>0&&<section className="section-block"><Eyebrow>Selected evidence</Eyebrow><h2 className="section-title">Karya dan kontribusi terpilih</h2><div className="mt-7 space-y-4">{profile.evidence.map(e=><Evidence key={`${e.title}-${e.year}`} item={e}/>)}</div></section>}
        {profile.experience.length>0&&<section className="section-block"><Eyebrow>Experience</Eyebrow><h2 className="section-title">Perjalanan profesional terpilih</h2><div className="relative mt-7 border-l border-[#cabdac] pl-7">{profile.experience.map(x=><article key={`${x.organization}-${x.role}`} className="relative pb-9 last:pb-0 before:absolute before:-left-[33px] before:top-1 before:h-3 before:w-3 before:rounded-full before:border-2 before:border-[#f6f2eb] before:bg-[#bd7937]"><p className="text-xs font-bold uppercase tracking-[.12em] text-[#a45e28]">{x.period}</p><h3 className="mt-2 text-lg font-extrabold">{x.role}</h3><p className="font-semibold text-slate-500">{x.organization}</p><p className="mt-3 text-sm leading-6 text-slate-600">{x.summary}</p></article>)}</div></section>}
      </div>
      <aside><div className="rounded-2xl border border-[#dcd3c7] bg-[#fffaf3] p-6 lg:sticky lg:top-28"><Eyebrow>Profile fit</Eyebrow><h2 className="mt-3 text-xl font-extrabold">Cocok untuk siapa?</h2><MetaList label="Audience" items={profile.audiences}/><MetaList label="Format" items={profile.deliveryModes}/><MetaList label="Bahasa" items={profile.languages}/><Link href="/contact" className="focus-ring mt-7 flex min-h-12 items-center justify-center rounded-lg bg-[#17212c] px-5 text-center text-sm font-bold text-white hover:bg-[#263646]">Diskusikan kebutuhan Anda</Link></div></aside>
    </section>
  </main>
}
function Info({term,value}:{term:string;value:string}){return <div><dt className="text-slate-500">{term}</dt><dd className="mt-1 font-bold capitalize text-slate-200">{value}</dd></div>}
function Eyebrow({children}:{children:React.ReactNode}){return <p className="text-xs font-extrabold uppercase tracking-[.17em] text-[#a75f27]">{children}</p>}
function MetaList({label,items}:{label:string;items:string[]}){if(!items.length)return null;return <div className="mt-6 border-t border-[#e5dcd0] pt-5"><h3 className="text-xs font-extrabold uppercase tracking-[.14em] text-slate-400">{label}</h3><ul className="mt-3 space-y-2 text-sm font-semibold text-slate-700">{items.map(x=><li key={x}>— {x}</li>)}</ul></div>}
function Evidence({item}:{item:EditorialProfile["evidence"][number]}){const href=safeExternalUrl(item.sourceUrl);return <article className="grid gap-4 rounded-xl border border-[#dcd3c7] bg-white/60 p-5 sm:grid-cols-[120px_1fr_auto] sm:items-center"><div><p className="text-xs font-bold uppercase tracking-[.12em] text-[#a75f27]">{item.type}</p>{item.year&&<p className="mt-1 text-xs text-slate-400">{item.year}</p>}</div><div><h3 className="font-extrabold">{item.title}</h3><p className="mt-1 text-sm leading-6 text-slate-600">{item.context}</p></div>{href&&<a href={href} target="_blank" rel="noopener noreferrer" className="focus-ring text-sm font-bold text-[#934e1d]" aria-label={`Buka sumber ${item.title}`}>Sumber <Arrow/></a>}</article>}
function formatDate(value:string){const date=new Date(value);return Number.isNaN(date.getTime())?value:new Intl.DateTimeFormat("id-ID",{day:"numeric",month:"long",year:"numeric"}).format(date)}
