"use client";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { DIRECT_NAV, TYPED_NAV_PANELS as NAV_PANELS, type NavigationPanel } from "./navigation-contract";
import { CLOSED_PANEL_STATE, shouldSchedulePointerClose, transitionPanelInteraction, type PanelInteractionState } from "./panel-interaction-state";

type PanelId = NavigationPanel["id"] | null;
const INITIAL_OPEN_DELAY=320, SWITCH_OPEN_DELAY=150, CLOSE_DELAY=320;
type PreviewState={initialPanel?:Exclude<PanelId,null>;initialMobile?:boolean;initialSection?:Exclude<PanelId,null>;initialScrolled?:boolean};
export function SkillaryMegaNavPreview({initialPanel,initialMobile=false,initialSection,initialScrolled=false}:PreviewState={}){
  const initialState:PanelInteractionState<Exclude<PanelId,null>>=initialPanel?{mode:"clickPinned",panelId:initialPanel}:CLOSED_PANEL_STATE;
  const [panelState,setPanelState]=useState(initialState),[mobile,setMobile]=useState(initialMobile),[mobileSection,setMobileSection]=useState<PanelId>(initialSection??null),[scrolled,setScrolled]=useState(initialScrolled);
  const open=panelState.panelId;
  const stateRef=useRef(panelState),root=useRef<HTMLElement>(null),triggers=useRef<Record<string,HTMLButtonElement|null>>({}),timer=useRef<ReturnType<typeof setTimeout>|null>(null);
  const updateState=(next:typeof panelState)=>{stateRef.current=next;setPanelState(next)};
  const clear=()=>{if(timer.current){clearTimeout(timer.current);timer.current=null}};
  const close=(restore=false)=>{clear();const previous=stateRef.current.panelId;updateState(CLOSED_PANEL_STATE);if(restore&&previous)requestAnimationFrame(()=>triggers.current[previous]?.focus())};
  const scheduleOpen=(id:Exclude<PanelId,null>)=>{clear();if(stateRef.current.mode==="clickPinned"||stateRef.current.mode==="keyboardOpen")return;const delay=stateRef.current.panelId&&stateRef.current.panelId!==id?SWITCH_OPEN_DELAY:INITIAL_OPEN_DELAY;timer.current=setTimeout(()=>updateState(transitionPanelInteraction(stateRef.current,{type:"hover-open",panelId:id})),delay)};
  const scheduleClose=()=>{clear();if(!shouldSchedulePointerClose(stateRef.current))return;timer.current=setTimeout(()=>updateState(CLOSED_PANEL_STATE),CLOSE_DELAY)};
  useEffect(()=>{
    if(!initialScrolled)return;
    const frame=requestAnimationFrame(()=>window.scrollTo({top:720,behavior:"instant"}));
    return()=>cancelAnimationFrame(frame);
  },[initialScrolled]);
  // Ref-backed close reads the latest state and intentionally remains outside effect dependencies.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(()=>{const onScroll=()=>{const next=window.scrollY>52;setScrolled(next);if(stateRef.current.panelId&&Math.abs(window.scrollY)>12)close()};onScroll();window.addEventListener("scroll",onScroll,{passive:true});return()=>window.removeEventListener("scroll",onScroll)},[]);
  // Ref-backed close reads the latest state and intentionally remains outside effect dependencies.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(()=>{const outside=(e:PointerEvent)=>{if(root.current&&!root.current.contains(e.target as Node))close()};const esc=(e:KeyboardEvent)=>{if(e.key==="Escape"){if(mobile){setMobile(false);setMobileSection(null)}else close(true)}};document.addEventListener("pointerdown",outside);document.addEventListener("keydown",esc);return()=>{document.removeEventListener("pointerdown",outside);document.removeEventListener("keydown",esc)}},[mobile]);
  useEffect(()=>{document.body.style.overflow=mobile?"hidden":"";return()=>{document.body.style.overflow=""}},[mobile]);
  const toggle=(id:NavigationPanel["id"],keyboard:boolean)=>{clear();updateState(transitionPanelInteraction(stateRef.current,{type:keyboard?"keyboard-toggle":"click-toggle",panelId:id}))};
  return <>
    <header ref={root} className="fixed inset-x-0 top-0 z-50 text-white">
      <div className={`overflow-hidden transition-[max-height,opacity] duration-300 ${scrolled?"max-h-0 opacity-0":"max-h-11 opacity-100"}`} style={{background:"radial-gradient(ellipse 55% 220% at 50% 0%,rgba(255,120,30,.85),rgba(150,55,10,.55) 40%,#0d101c 100%)"}}><div className="mx-auto flex h-11 max-w-7xl items-center justify-center gap-3 px-4 text-xs font-semibold"><span className="truncate">✦ BARU: Skillary Events — kelas singkat untuk skill kerja profesional</span><Link href="/events" className="rounded-full border border-white/30 bg-white/10 px-3 py-1 font-bold hover:bg-white/20">Lihat Events</Link></div></div>
      <div className={`relative transition-all duration-300 ${scrolled?"px-3 pt-3 md:px-4":"px-0 pt-0"}`}>
        <div className={`mx-auto flex h-14 items-center justify-between bg-[#0d101c] transition-all duration-300 md:h-16 ${scrolled?"max-w-5xl rounded-full px-3 shadow-2xl md:px-5":"max-w-[120rem] rounded-none px-4 md:px-8"}`}>
          <Link href="/" className="flex shrink-0 items-center gap-2.5 rounded-md focus:outline-none focus-visible:ring-2 focus-visible:ring-[#f0b65b]"><Image src="/logo.png" alt="Skillary" width={44} height={24} priority className="h-6 w-auto object-contain"/><span className="text-base font-extrabold tracking-tight">Skillary</span></Link>
          <nav aria-label="Navigasi utama" className="hidden items-center gap-1 lg:flex">
             {NAV_PANELS.map(panel=><div key={panel.id} className="relative" onPointerEnter={()=>scheduleOpen(panel.id)} onPointerLeave={scheduleClose}><button ref={el=>{triggers.current[panel.id]=el} } type="button" aria-expanded={open===panel.id} aria-controls={`mega-${panel.id}`} onClick={event=>toggle(panel.id,event.detail===0)} className={`flex min-h-11 items-center gap-1.5 rounded-full px-3 text-sm font-semibold outline-none transition focus-visible:ring-2 focus-visible:ring-[#f0b65b] ${open===panel.id?"bg-white/10 text-white":"text-white/65 hover:text-white"}`}>{panel.label}<Chevron open={open===panel.id}/></button></div>)}
            {DIRECT_NAV.map(n=><Link key={n.id} href={n.href} className="flex min-h-11 items-center rounded-full px-3 text-sm font-semibold text-white/65 outline-none transition hover:text-white focus-visible:ring-2 focus-visible:ring-[#f0b65b]">{n.label}</Link>)}
          </nav>
          <div className="hidden items-center gap-3 lg:flex"><Link href="/login" className="rounded-full px-3 py-2 text-sm font-semibold text-white/75 outline-none hover:text-white focus-visible:ring-2 focus-visible:ring-[#f0b65b]">Masuk</Link><Link href="/programs" className="rounded-full bg-white px-5 py-2.5 text-sm font-extrabold text-[#0f172a] outline-none transition hover:bg-[#fff4e5] focus-visible:ring-2 focus-visible:ring-[#f0b65b]">Jelajahi Program</Link></div>
          <div className="flex items-center gap-2 lg:hidden"><Link href="/programs" className="rounded-full bg-white px-4 py-2 text-xs font-extrabold text-[#0f172a]">Program</Link><button type="button" aria-label={mobile?"Tutup navigasi":"Buka navigasi"} aria-expanded={mobile} aria-controls="mobile-navigation" onClick={()=>{setMobile(v=>!v);updateState(CLOSED_PANEL_STATE)}} className="flex h-10 w-10 items-center justify-center rounded-full outline-none hover:bg-white/10 focus-visible:ring-2 focus-visible:ring-[#f0b65b]">{mobile?<CloseIcon/>:<MenuIcon/>}</button></div>
        </div>
         {NAV_PANELS.map(panel=><MegaPanel key={panel.id} panel={panel} visible={open===panel.id} onEnter={()=>{clear();const next=transitionPanelInteraction(stateRef.current,{type:"hover-open",panelId:panel.id});if(next!==stateRef.current)updateState(next)}} onLeave={scheduleClose}/>) }
      </div>
    </header>
    {open&&<button aria-label="Tutup menu navigasi" onClick={()=>close()} className="fixed inset-0 z-40 hidden cursor-default bg-[#080b13]/15 backdrop-blur-[1px] lg:block"/>}
    <div id="mobile-navigation" className={`fixed inset-0 z-40 bg-[#0d101c] px-5 pb-8 pt-28 text-white transition duration-300 lg:hidden ${mobile?"visible translate-y-0 opacity-100":"invisible -translate-y-3 opacity-0"}`}><nav aria-label="Navigasi seluler" className="mx-auto flex h-full max-w-xl flex-col overflow-y-auto pt-4">{NAV_PANELS.map(panel=><div key={panel.id} className="border-b border-white/10"><button type="button" aria-expanded={mobileSection===panel.id} aria-controls={`mobile-${panel.id}`} onClick={()=>setMobileSection(v=>v===panel.id?null:panel.id)} className="flex min-h-16 w-full items-center justify-between text-left text-lg font-bold">{panel.label}<Chevron open={mobileSection===panel.id}/></button>{mobileSection===panel.id&&<div id={`mobile-${panel.id}`} className="pb-5"><Link href={panel.href} className="block py-2 text-sm font-bold text-[#f0b65b]">{panel.title} →</Link>{panel.groups.flatMap(g=>g.links).map(x=><Link key={x.id} href={x.href} className="block py-2.5 text-sm font-semibold text-white/75">{x.label}</Link>)}{panel.action&&<Link href={panel.action.href} className="mt-3 inline-flex rounded-full border border-white/20 px-4 py-2.5 text-sm font-bold">{panel.action.label}</Link>}</div>}</div>)}{DIRECT_NAV.map(n=><Link key={n.id} href={n.href} className="flex min-h-16 items-center border-b border-white/10 text-lg font-bold">{n.label}<span className="ml-auto text-white/35">→</span></Link>)}<div className="mt-auto grid grid-cols-2 gap-3 pt-7"><Link href="/login" className="rounded-full border border-white/20 px-4 py-3 text-center text-sm font-bold">Masuk</Link><Link href="/programs" className="rounded-full bg-white px-4 py-3 text-center text-sm font-extrabold text-[#0f172a]">Jelajahi Program</Link></div></nav></div>
  </>;
}
function MegaPanel({panel,visible,onEnter,onLeave}:{panel:NavigationPanel;visible:boolean;onEnter:()=>void;onLeave:()=>void}){return <div id={`mega-${panel.id}`} aria-hidden={!visible} inert={!visible} onPointerEnter={onEnter} onPointerLeave={onLeave} className={`absolute left-1/2 top-full hidden w-[min(1200px,calc(100vw-32px))] -translate-x-1/2 pt-1 transition duration-200 lg:block ${visible?"visible translate-y-0 opacity-100":"invisible -translate-y-2 opacity-0 pointer-events-none"}`}><div className="min-h-[25rem] overflow-hidden rounded-b-[24px] rounded-t-xl border border-[#eadfd2] bg-[#fffaf4] text-[#182230] shadow-[0_30px_80px_rgba(7,10,18,.28)]"><div className="grid min-h-[25rem] grid-cols-[minmax(0,.9fr)_minmax(0,1.1fr)_minmax(0,1fr)] gap-7 p-7 xl:gap-9 xl:p-8"><Link href={panel.href} className="group relative overflow-hidden rounded-2xl bg-[#151f2b] p-7 text-white outline-none focus-visible:ring-2 focus-visible:ring-[#d99335]"><div className="absolute inset-0 opacity-30 [background:radial-gradient(circle_at_95%_0%,#f59e0b,transparent_46%)]"/><p className="relative text-[11px] font-extrabold uppercase tracking-[.17em] text-[#efb75c]">{panel.eyebrow}</p><h2 className="relative mt-5 text-2xl font-extrabold leading-tight tracking-[-.03em]">{panel.title}</h2><p className="relative mt-4 text-sm leading-6 text-white/60">{panel.description}</p><span className="relative mt-8 inline-flex text-sm font-extrabold text-[#f3c273]">Jelajahi sekarang <span className="ml-2 transition group-hover:translate-x-1">→</span></span></Link>{panel.groups.map(g=><section key={g.title} aria-labelledby={`${panel.id}-${g.title.replaceAll(" ","-")}`}><h2 id={`${panel.id}-${g.title.replaceAll(" ","-")}`} className="text-[11px] font-extrabold uppercase tracking-[.16em] text-[#9a6a39]">{g.title}</h2><ul className="mt-4 space-y-1">{g.links.map(x=><li key={x.id}><Link href={x.href} className="group block rounded-xl px-3 py-3 outline-none hover:bg-[#f4eadc] focus-visible:ring-2 focus-visible:ring-[#d99335]"><span className="flex items-center justify-between text-sm font-extrabold">{x.label}<span className="text-[#bc7837] opacity-0 transition group-hover:translate-x-1 group-hover:opacity-100">→</span></span><span className="mt-1 block text-xs leading-5 text-slate-500">{x.description}</span></Link></li>)}</ul>{panel.action&&g===panel.groups.at(-1)&&<Link href={panel.action.href} className="mt-4 inline-flex rounded-full bg-[#17212d] px-5 py-3 text-sm font-extrabold text-white outline-none hover:bg-[#293a4d] focus-visible:ring-2 focus-visible:ring-[#d99335]">{panel.action.label} →</Link>}</section>)}</div></div></div>}
function Chevron({open}:{open:boolean}){return <svg aria-hidden="true" className={`h-3.5 w-3.5 transition ${open?"rotate-180":""}`} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2.5"><path strokeLinecap="round" strokeLinejoin="round" d="m6 9 6 6 6-6"/></svg>}
function MenuIcon(){return <svg aria-hidden="true" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2.5"><path strokeLinecap="round" d="M4 7h16M4 12h16M4 17h16"/></svg>}
function CloseIcon(){return <svg aria-hidden="true" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2.5"><path strokeLinecap="round" d="m6 6 12 12M18 6 6 18"/></svg>}
